### ISSUE TITLE
Parse inline HTML

### ISSUE THREAD

**Issue by birhoff** [birhoff/mdast-util-to-bemjson#3]
> Распаршивать заинлайненный HTML в markdown

**Comment by birhoff** [comment]
@tadatuta можешь более подробно написать что тут хочется. Можно просто пример

**Comment by tadatuta** [comment]
```
# это заголовок в md
<h1>это тоже заголовок в md, но в html</h1>
```
хочется опционально получать дерево с одинаковыми узлами для первого и для второго варианта

**Comment by birhoff** [comment]
We try to support this at parent package.
